version: '3'

services:
  postgres-primary:
    image: postgres:latest
    container_name: postgres-primary
    environment:
      POSTGRES_PASSWORD: your_password
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  postgres-replica:
    image: postgres:latest
    container_name: postgres-replica
    environment:
      POSTGRES_PASSWORD: your_password
      PGDATA: /var/lib/postgresql/data/pgdata
      PATRONI_RESTAPI_PASSWORD: your_patroni_password
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  patroni:
    image: ongres/patroni
    container_name: patroni
    environment:
      PATRONI_RESTAPI_PASSWORD: your_patroni_password
    depends_on:
      - postgres-primary
      - postgres-replica
    ports:
      - "8008:8008"

volumes:
  postgres-data:
