# Use a imagem oficial do Ubuntu
FROM ubuntu:latest

# Atualiza os pacotes e instala o software necessário
RUN apt-get update && apt-get install -y \
    curl \
    vim

# Define o comando padrão
CMD ["bash"]
