version: '3.7'
services:
  pg-publisher:
    container_name: pg-publisher
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - publisher-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pg-subscriber:
    container_name: pg-subscriber
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - subscriber-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  publisher-data:
  subscriber-data:
